### ISSUE TITLE
Update to PyPy3.5 v6.0

### ISSUE THREAD

**Issue by ohadravid** [conda-forge/pypy3.5-feedstock#2]
1. There is a newer version! http://doc.pypy.org/en/latest/release-v6.0.0.html
2. `conda-build` is now in version 3, so we should be able to remove the ugly `wget` from the script and use

```yaml
source:
  - url: https://bitbucket.org/pypy/pypy/downloads/pypy3-v{{ version }}-src.tar.bz2
    fn: pypy3-v{{ version }}-src.tar.bz2
    sha256: f5548e06e2fc0c24ec8b6e3c5b09f90081818f7caa3e436dc312592611724713
    folder: pypy3
    patches:
      - tklib_build.patch

  - url: https://bitbucket.org/pypy/pypy/downloads/pypy2-v5.9.0-osx64.tar.bz2  # [osx]
    fn: pypy2-v5.9.0-osx64.tar.bz2  # [osx]
    sha256: 94de50ed80c7f6392ed356c03fd54cdc84858df43ad21e9e971d1b6da0f6b867  # [osx]
    folder: pypy2-osx  # [osx]

...

    license_file: pypy3/LICENSE
```

```bash
PYPY3_SRC_DIR=$SRC_DIR/pypy3
...
    export PYTHON=$SRC_DIR/pypy2-osx/bin/pypy
...
   export PYTHON=${PREFIX}/bin/python
```
